---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: python-secret-key
  namespace: default
spec:
  encryptedData:
    SECRET_KEY: AgBbWfJrlJKy+IBtr180kVqc1Q3NNM2wgYBr2XUt4pYqBE5y57HNLjXMfcY2viNMaoF/n8A4PnD0QujVY06odF19vvgqmyhZVpWz+0w7Px4aqumE0FCV2kFCKZF3DDOusvaK7QCvBgj3yjzy5AQAWfs6Dvzk3RtXRFAgwcMfM8PNbgFh0inj66Q1vpaKaIfuGs61A0M2KJCbwar9Njw4FTBHlSAVOFhqzVM23SEUVmrsZpAk+8hMMwwnL/6OeDW+5LCY247Fvf6nzQtaEDcE7WUWSGAJxO98usayCiCbLgxkCaNwWoq2hNqu0rb04K/oSx16soUyM/Ha3BI+VNNyoFkc6OpiQjTs6NHnfPmQ//UnVrNvktQCzcPhGlTIIHDdlw17UJ0Vjn2WvRhPjRpF7zcYghcAiLnGzQJq/ebFY5daz5nELRaBv0V/oU4koDRJhJ0IlYINXwKo08rJ3+8Cd0Pg3UUQnaojI3tBryriVPKcQIFwBk6/VpputrmTBInxTnLlRm6JLQaGbmRy12TqOmkxwxe210TZVMi2Gzgbwf665mSuPGB79rH4HbwMsOw4q7fr90G52N0O/S2Nd1zr94RAwa2CdIHwzmqDuZmdi5f1VfL5VSO3TLd6bFd3bTv1XCkuzs4HWLvO+T+oQ0Rb+g7kcO+YdkLiPkVGDdntz20hl9wd0RtA3phtIhi2f13Ldbua1Zb0n0c5Zweq7d3tz1LK6NheFhY=
  template:
    metadata:
      creationTimestamp: null
      name: python-secret-key
      namespace: default
    type: Opaque
